# generated by Claude 3.7 using this prompt + some tweaks:
# author: Jared Bard
# date: 25/03/2024
# Write a python program that cleans up data in a .csv into "tidy" format.
# The program should be designed to run on a command line and use argparse.
# First argument is the input csv.
# Second argument is the output  file_tidy.csv
# Third argument is optional and is the size of the matrix (integer with value of at least 1). Default to 3

# The beginning of the input.csv looks like this:
# "
# User: USER,Path: C:\Program Files (x86)\BMG\CLARIOstar\User\Data,Test run no.: 294
# Test name: FRET_549_646,Date: 3/20/2025,Time: 12:09:50 PM

# Fluorescence (FI), multichromatic

# A01
# X1 Raw Data (Well scan) 550-10/590-10
# 1602,1629,1611
# 1638,1572,1547
# 1603,1603,1600

# A02
# X1 Raw Data (Well scan) 550-10/590-10
# 1870,1736,1622
# 1942,1953,1870
# 1642,1472,1613

# A03
# X2 Raw Data (Well scan) 550-10/590-10
# 1198,1107,1019
# 1088,1098,1049
# 1100,1002,1073
# "

# The program should scan through line by line until encountering a line like "A01" which encodes the "Well" variable
# It should then take the next line as the "Channel" variable
# The next X lines (where X is the size of the matrix) is a table of data. Separate them out with a Matrix_ij variable into a list

# Finally, once the whole file is scanned, format the results using pandas into a dataframe (Filename,Well,Channel,Matrix_ij,Value) and use pandas to export the dataframe as a csv

import argparse
import pandas as pd
import os
import re

WELL_PATTERN = re.compile(r'^[A-H]\d{2}$')


def _is_well_identifier(text):
    return bool(WELL_PATTERN.match(text.strip()))


def _coerce_float(value):
    value = value.strip()
    if value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None

def parse_csv(input_file, matrix_size=3):
    """
    Parse the custom CSV format and convert to tidy data.
    
    Args:
        input_file (str): Path to input CSV file
        matrix_size (int): Size of the matrix (default: 3)
        
    Returns:
        pandas.DataFrame: Tidy data frame
    """
    # Extract filename from the input path
    filename = os.path.basename(input_file)
    
    # Data storage
    data = []
    
    # Try different encodings
    encodings = ['utf-8', 'latin-1', 'cp1252']
    lines = None
    
    for encoding in encodings:
        try:
            with open(input_file, 'r', encoding=encoding) as f:
                lines = f.readlines()
            print(f"Successfully read file using {encoding} encoding")
            break  # If successful, exit the loop
        except UnicodeDecodeError:
            continue  # Try the next encoding
    
    if lines is None:
        raise ValueError(f"Could not decode the file {input_file} with any of the attempted encodings.")
    
    line_index = 0
    num_lines = len(lines)

    while line_index < num_lines:
        line = lines[line_index].strip()

        if not _is_well_identifier(line):
            line_index += 1
            continue

        well = line
        line_index += 1

        while line_index < num_lines and lines[line_index].strip() == "":
            line_index += 1

        if line_index >= num_lines:
            break

        channel = lines[line_index].strip()
        line_index += 1

        row_idx = 0
        while line_index < num_lines:
            row_line = lines[line_index].strip()

            if row_line == "" or _is_well_identifier(row_line):
                break

            cells = row_line.split(',')
            numeric_found = False

            for col_idx, cell in enumerate(cells):
                value = _coerce_float(cell)
                if value is None:
                    continue

                numeric_found = True
                matrix_position = f"{row_idx + 1}-{col_idx + 1}"
                data.append({
                    'Filename': filename,
                    'Well': well,
                    'Channel': channel,
                    'Matrix_ij': matrix_position,
                    'Value': value
                })

            if not numeric_found:
                break

            row_idx += 1
            line_index += 1
    
    # Convert to pandas DataFrame
    return pd.DataFrame(data)

def main():
    """
    Main function to parse arguments and process the CSV file.
    """
    parser = argparse.ArgumentParser(description='Clean up CSV data into tidy format.')
    parser.add_argument('input_csv', help='Path to input CSV file')
    parser.add_argument('--output_csv', help='Path to output CSV file (default: input_basename_tidy.csv)')
    parser.add_argument('--matrix_size', type=int, default=3, 
                        help='Size of the matrix (default: 3)')
    
    args = parser.parse_args()
    
    # Set default output filename if not provided
    if not args.output_csv:
        input_dir = os.path.dirname(args.input_csv)
        input_basename = os.path.splitext(os.path.basename(args.input_csv))[0]
        args.output_csv = os.path.join(input_dir, f"{input_basename}_tidy.csv")
    
    # Validate matrix size
    if args.matrix_size < 1:
        print("Error: Matrix size must be at least 1")
        return
    
    try:
        # Parse the input CSV and convert to tidy format
        df = parse_csv(args.input_csv, args.matrix_size)
    
        if df.empty:
            df = pd.DataFrame(columns=['Filename', 'Well', 'Channel', 'Matrix_ij', 'Value'])
        else:
            # Sort the DataFrame by Filename, Well, Channel, then matrix_ij
            df = df.sort_values(by=['Filename', 'Well', 'Channel', 'Matrix_ij'])
        
        # Save to output CSV
        df.to_csv(args.output_csv, index=False)
        print(f"Tidy data saved to {args.output_csv}")
        print(f"Processed {len(df)} data points")
    except Exception as e:
        print(f"Error processing file: {e}")

if __name__ == "__main__":
    main()