# generated by Claude 3.7 using this prompt + some tweaks:
# author: Jared Bard
# date: 25/03/2024
# Write a python program that cleans up data in a .csv into "tidy" format.
# The program should be designed to run on a command line and use argparse.
# First argument is the input csv.
# Second argument is the output  file_tidy.csv
# Adapted on 4/28/25 to analyze luminescence data

# The beginning of the input.csv looks like this:
# User: USER,Path: C:\Program Files (x86)\BMG\CLARIOstar\User\Data,Test run no.: 336
# Test name: NL_384,Date: 4/27/2025,Time: 7:51:31 PM

# Luminescence

# Raw Data (470-80)

# ,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,
# A,,,,,,,,,,,,,,,,,,,,,,,,
# B,,502,,1212,,1845,,1083,,8595,,7651,,10084,,3074,,5178,,66759,,,,
# C,,6126,,2048,,419,,825,,11851,,7166,,11189,,2958,,13913,,108040,,,,
# D,,2286,,978,,714,,887,,10223,,6732,,9080,,2165,,5422,,74036,,,,
# E,,,,,,,,,,,,,,,,,,,,,,,,
# F,,18260,,16999,,2713,,24710,,292343,,,,,,,,,,,,,,
# G,,9785,,14567,,10533,,24817,,352583,,,,,,,,,,,,,,
# H,,12396,,13936,,4278,,28448,,305739,,,,,,,,,,,,,,
# I,,,,,,,,,,,,,,,,,,,,,,,,
# J,,,,,,,,,,,,,,,,,,,,,,,,
# K,,,,,,,,,,,,,,,,,,,,,,,,
# L,,,,,,,,,,,,,,,,,,,,,,,,
# M,,9413,,2098,,2281,,17849,,190914,,5957,,10171,,11265,,13875,,58791,,47,,
# N,,72905,,16247,,2753,,12315,,145662,,1975,,8880,,2749,,5489,,62567,,53,,
# O,,7851,,16391,,2582,,11779,,169541,,16412,,6456,,10761,,5456,,64061,,44,,
# P,,,,,,,,,,,,,,,,,,,,,,,,

 
# Well,Content,Raw Data (470-80),
# B02,Sample X1,502,
# B04,Sample X4,1212,
# B06,Sample X7,1845,
# B08,Sample X10,1083,
# B10,Sample X13,8595,

# The program should scan through line by line until encountering a line like "Well,Content,"
# The next X lines (where X is the size of the matrix) is a table of data.

# Finally, once the whole file is scanned, format the results using pandas into a dataframe (Filename,Well,Channel,Value) and use pandas to export the dataframe as a csv

import argparse
import pandas as pd
import os
import re

def parse_csv(input_file):
    """
    Parse the custom CSV format and convert to tidy data.
    
    Args:
        input_file (str): Path to input CSV file
        matrix_size (int): Size of the matrix (default: 3)
        
    Returns:
        pandas.DataFrame: Tidy data frame
    """
    # Extract filename from the input path
    filename = os.path.basename(input_file)
    
    # Data storage
    data = []
    
    # Try different encodings
    encodings = ['utf-8', 'latin-1', 'cp1252']
    lines = None
    
    for encoding in encodings:
        try:
            with open(input_file, 'r', encoding=encoding) as f:
                lines = f.readlines()
            print(f"Successfully read file using {encoding} encoding")
            break  # If successful, exit the loop
        except UnicodeDecodeError:
            continue  # Try the next encoding
    
    if lines is None:
        raise ValueError(f"Could not decode the file {input_file} with any of the attempted encodings.")
    
    line_index = 0
    num_lines = len(lines)
    record_flag = False
    
    # Skip header until we find a well identifier
    while line_index < num_lines:
        line = lines[line_index].strip()
        print(line)
        
        if not record_flag: # scan for first line of the data
            if line.startswith("Well,Content,"):
                # Extract the Channel value (everything after "Well,Content,")
                channel = line.split(",")[2]
                
                # Now you have the channel value stored in the variable
                print(f"Found channel: {channel}")
                line_index += 1
                record_flag = True
                continue
            else: # haven't found the data yet
                line_index += 1
                continue
        else: # recording data!
            if line == "": # have we reached the end?
                break
            else:
                row = line.split(",")
                well = row[0]
                try:
                    value = float(row[2])
                except ValueError:
                    # Not numerical data
                    break
                data.append({
                    'Filename': filename,
                    'Well': well,
                    'Channel': channel,
                    'Value': value
                })
                line_index += 1
    
    # Convert to pandas DataFrame
    return pd.DataFrame(data)

def main():
    """
    Main function to parse arguments and process the CSV file.
    """
    parser = argparse.ArgumentParser(description='Clean up CSV data into tidy format.')
    parser.add_argument('input_csv', help='Path to input CSV file')
    parser.add_argument('--output_csv', help='Path to output CSV file (default: input_basename_tidy.csv)')
    
    args = parser.parse_args()
    
    # Set default output filename if not provided
    if not args.output_csv:
        input_dir = os.path.dirname(args.input_csv)
        input_basename = os.path.splitext(os.path.basename(args.input_csv))[0]
        args.output_csv = os.path.join(input_dir, f"{input_basename}_tidy.csv")
    
    try:
        # Parse the input CSV and convert to tidy format
        df = parse_csv(args.input_csv)
    
        # Sort the DataFrame by Filename, Well, Channel, then matrix_ij
        df = df.sort_values(by=['Filename', 'Well', 'Channel'])
        
        # Save to output CSV
        df.to_csv(args.output_csv, index=False)
        print(f"Tidy data saved to {args.output_csv}")
        print(f"Processed {len(df)} data points")
    except Exception as e:
        print(f"Error processing file: {e}")

if __name__ == "__main__":
    main()